"""Sphinx configuration for diversify documentation.
    This was generated by claude and not reviewed. (We assume WYSIWYG and only check the generated docs, not the conf.py itself.)
"""

import sys
import tomllib
from pathlib import Path

# -- Path setup --------------------------------------------------------
_root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_root))

# -- Project information ------------------------------------------------
project = "diversify-text"
copyright = "2025, Anna Wegmann"
author = "Anna Wegmann"
release = tomllib.loads((_root / "pyproject.toml").read_text())["project"]["version"]

# -- General configuration ----------------------------------------------
extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
]

# Mock heavy dependencies so docs build without torch, transformers, etc.
autodoc_mock_imports = [
    "torch",
    "transformers",
    "sentence_transformers",
    "sentencepiece",
    "tiktoken",
    "protobuf",
    "huggingface_hub",
    "tqdm",
    "mutual_implication_score",
    "pysbd",
]

# Napoleon settings (NumPy-style docstrings)
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_use_param = True
napoleon_use_rtype = True

# Autodoc settings
autodoc_member_order = "bysource"
autodoc_typehints = "description"
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
}

# Intersphinx for linking to Python stdlib docs
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# -- HTML output ---------------------------------------------------------
html_theme = "sphinx_rtd_theme"
html_title = "diversify-text"

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- Generated listings --------------------------------------------------
# The styles page shows TinyStyler's banks with example texts.  The
# listings are generated from the code at every docs build, so the page
# cannot drift from the banks.  Written to docs/_generated/ (gitignored).


def _generate_tinystyler_listings() -> None:
    from diversify_text.method.tinystyler.bank import (
        TINYSTYLER_STYLE_BANK,
        TINYSTYLER_SURFACE_STYLE_BANK,
        TINYSTYLER_UNUSUAL_STYLE_BANK,
    )

    def entry(term, examples):
        lines = [term]
        for text in examples[:2]:
            text = " ".join(text.split()).replace("`", "'")
            if len(text) > 90:
                text = text[:87] + "..."
            lines.append(f"   - ``{text}``")
        lines.append("")
        return lines

    out = Path(__file__).parent / "_generated"
    out.mkdir(exist_ok=True)

    lines = []
    for i, (name, examples) in enumerate(TINYSTYLER_STYLE_BANK.items()):
        lines += entry(f"``{name}`` — index {i}", examples)
    (out / "tinystyler_bank.inc").write_text("\n".join(lines), encoding="utf-8")

    lines = []
    for name, examples in TINYSTYLER_UNUSUAL_STYLE_BANK.items():
        lines += entry(f"``{name}``", examples)
    (out / "tinystyler_unusual.inc").write_text("\n".join(lines), encoding="utf-8")

    lines = []
    for name, examples in TINYSTYLER_SURFACE_STYLE_BANK.items():
        lines += entry(f"``{name}``", examples)
    (out / "tinystyler_surface.inc").write_text("\n".join(lines), encoding="utf-8")


_generate_tinystyler_listings()
