"""Sphinx configuration for diversify documentation.
    This was generated by claude and not reviewed. (We assume WYSIWYG and only check the generated docs, not the conf.py itself.)
"""

import sys
import tomllib
from pathlib import Path

# -- Path setup --------------------------------------------------------
_root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_root))

# -- Project information ------------------------------------------------
project = "diversify-text"
copyright = "2025, Anna Wegmann"
author = "Anna Wegmann"
release = tomllib.loads((_root / "pyproject.toml").read_text())["project"]["version"]

# -- General configuration ----------------------------------------------
extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
]

# Mock heavy dependencies so docs build without torch, transformers, etc.
autodoc_mock_imports = [
    "torch",
    "transformers",
    "sentence_transformers",
    "sentencepiece",
    "tiktoken",
    "protobuf",
    "huggingface_hub",
    "tqdm",
    "mutual_implication_score",
    "pysbd",
]

# Napoleon settings (NumPy-style docstrings)
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_use_param = True
napoleon_use_rtype = True

# Autodoc settings
autodoc_member_order = "bysource"
autodoc_typehints = "description"
autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
}

# Intersphinx for linking to Python stdlib docs
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# -- HTML output ---------------------------------------------------------
html_theme = "sphinx_rtd_theme"
html_title = "diversify-text"

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- Generated listings --------------------------------------------------
# The styles page shows every bank with example texts.  The listings are
# generated from the code at every docs build, so the page cannot drift
# from the banks.  Written to docs/_generated/ (gitignored).


def _generate_style_listings() -> None:
    from diversify_text.method.tinystyler.bank import (
        TINYSTYLER_STYLE_BANK,
        TINYSTYLER_SURFACE_STYLE_BANK,
        TINYSTYLER_UNUSUAL_STYLE_BANK,
    )
    from diversify_text.method.zero_shot.bank import ZERO_SHOT_STYLE_BANK
    from diversify_text.styles import (
        DEFAULT_STYLE_BANK,
        SURFACE_STYLE_BANK,
        UNUSUAL_STYLE_BANK,
    )

    def entry(term, texts, count=2, width=90):
        lines = [term]
        for text in texts[:count]:
            text = " ".join(text.split()).replace("`", "'")
            if len(text) > width:
                text = text[: width - 3] + "..."
            lines.append(f"   - ``{text}``")
        lines.append("")
        return lines

    def write(filename, bank, indexed=False, count=2, width=90):
        lines = []
        for i, (name, texts) in enumerate(bank.items()):
            term = f"``{name}`` — index {i}" if indexed else f"``{name}``"
            lines += entry(term, texts, count=count, width=width)
        (out / filename).write_text("\n".join(lines), encoding="utf-8")

    out = Path(__file__).parent / "_generated"
    out.mkdir(exist_ok=True)

    write("tinystyler_bank.inc", TINYSTYLER_STYLE_BANK, indexed=True)
    write("tinystyler_unusual.inc", TINYSTYLER_UNUSUAL_STYLE_BANK)
    write("tinystyler_surface.inc", TINYSTYLER_SURFACE_STYLE_BANK)
    write("default_bank.inc", DEFAULT_STYLE_BANK, indexed=True)
    write("default_unusual.inc", UNUSUAL_STYLE_BANK)
    write("surface_bank.inc", SURFACE_STYLE_BANK)
    # Zero-shot styles are defined by one instruction, not example texts.
    write("zero_shot_bank.inc", ZERO_SHOT_STYLE_BANK,
          indexed=True, count=1, width=160)


_generate_style_listings()
